---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      dashy:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          dashy:
            image:
              repository: ghcr.io/lissy93/dashy
              tag: 4.4.4@sha256:2ff63efb26e0e6034b642298417e9a9b5374a39f10467cd7166dcc3a4f70986c
            env:
              TZ: America/Toronto
              DISABLE_CONFIG_BACKUPS: true
    service:
      dashy:
        ports:
          http:
            port: &mainPort 8080
    route:
      dashy:
        hostnames: ["dashy.zinn.ca"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: dashy
                port: *mainPort
    persistence:
      config:
        enabled: true
        existingClaim: dashy-config
        advancedMounts:
          dashy:
            dashy:
              - path: /app/user-data
      icons:
        enabled: true
        type: configMap
        name: dashy-icons
        advancedMounts:
          dashy:
            dashy:
              - path: /app/user-data/item-icons
                readOnly: true
      backup:
        existingClaim: self-hosted-backups
        advancedMounts:
          dashy:
            dashy:
              - path: /backups
                subPath: dashy
