[settings]
pipx.uvx = true

[tools]
"aqua:helm/helm" = "3.20.2"
"aqua:helmfile/helmfile" = "1.4.4"
"aqua:astral-sh/uv" = "latest"
"pipx:flux-local" = "latest"
"kubeconform" = "latest"
"npm:renovate" = "latest"
"node" = "24"
cilium-cli = "latest"
cilium-hubble = "latest"
helm-docs = "latest"
helm-ls = "latest"
kustomize = "latest"
