[tools]
"aqua:helm/helm" = "3.21.1"
"aqua:helmfile/helmfile" = "1.5.5"
"kubeconform" = "latest"
"npm:renovate" = "latest"
cilium-cli = "latest"
cilium-hubble = "latest"
helm-docs = "latest"
helm-ls = "latest"
kustomize = "latest"
prettier = "latest"
"github:home-operations/flate" = "v0.4.8"
