---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: echo-server
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      echo-server:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          echo-server:
            image:
              repository: ghcr.io/mendhak/http-https-echo
              tag: 41@sha256:2046be25f4a2c0bdda662ebfb7c2b7b60fc95c31d97987be143645a8a2194a40
            env:
              HTTP_PORT: &port 8080
              LOG_WITHOUT_NEWLINE: "true"
              LOG_IGNORE_PATH: "/healthz"
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            resources:
              requests:
                cpu: 5m
                memory: 64M
              limits:
                memory: 64M

    service:
      echo-server:
        ports:
          http:
            port: *port

    route:
      external:
        annotations:
          external-dns/is-public: "true"
          external-dns.alpha.kubernetes.io/target: external.zinn.ca
        hostnames: ["{{ .Release.Name }}.zinn.ca"]
        parentRefs:
          - name: envoy-external
            namespace: network
        rules:
          - backendRefs:
              - identifier: echo-server
                port: *port
