---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bichon
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      bichon:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            fsGroup: 4000
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 4000
            runAsNonRoot: true
            runAsUser: 4000
        containers:
          bichon:
            image:
              repository: docker.io/rustmailer/bichon
              tag: 1.0.1@sha256:4952ad1755c6bde02af9bdb8acafb1aa9969bcd31103e14213069e016a2cb0b7
            env:
              BICHON_HTTP_PORT: &httpPort 15630
              BICHON_LOG_LEVEL: info
              BICHON_PUBLIC_URL: https://bichon.zinn.ca
              BICHON_ROOT_DIR: /data
            envFrom:
              - secretRef:
                  name: bichon-secret
            # command:
            #   - /usr/bin/bash
            #   - -c
            #   - sleep 2000000
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *httpPort
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 2Gi
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      bichon:
        ports:
          http:
            port: *httpPort
    persistence:
      data:
        type: nfs
        path: /mnt/atlas/k8s/main/bichon
        server: ragnar.zinn.tech
    route:
      bichon:
        hostnames:
          - bichon.zinn.ca
        parentRefs:
          - name: envoy-internal
            namespace: network
