---
# yaml-language-server: $schema=https://schemas.zinn.ca/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: k8s-homelab
spec:
  discoveryFilters:
    - szinn/k8s-homelab
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        [pnpm ["pnpm run bundle"]
    - name: RENOVATE_PLATFORM_COMMIT
      value: "true"
  image: ghcr.io/renovatebot/renovate:43.110.3@sha256:e5f61c5feb9fe3e5887135337edf178a99e01f5c1438f7da99f58930cfb7c51d
  parallelism: 5
  provider:
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
