---
# yaml-language-server: $schema=https://schemas.zinn.ca/renovate-operator.mogenius.com/renovatejob_v1alpha1.json
apiVersion: renovate-operator.mogenius.com/v1alpha1
kind: RenovateJob
metadata:
  name: k8s-homelab
spec:
  discoveryFilters:
    - szinn/k8s-homelab
  extraEnv:
    - name: LOG_LEVEL
      value: debug
    - name: RENOVATE_ALLOWED_COMMANDS
      value: |-
        [pnpm ["pnpm run bundle"]
    - name: RENOVATE_GIT_AUTHOR
      value: "Jeeves <jeeves@noreply.github.com>"
    - name: RENOVATE_PLATFORM_COMMIT
      value: enabled
  image: ghcr.io/renovatebot/renovate:43.165.1@sha256:b1e44b4b22ded56a2ccd5f41edb764b8ef62dd537b3b32e60d676b0424e7bc06
  parallelism: 5
  provider:
    name: github
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
  schedule: 0 * * * *
  secretRef: renovate-secret
  webhook:
    enabled: true
