---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/kopiur.home-operations.com/snapshotpolicy_v1alpha1.json
apiVersion: kopiur.home-operations.com/v1alpha1
kind: SnapshotPolicy
metadata:
  name: ${APP}
spec:
  copyMethod: Snapshot
  credentialProjection:
    enabled: true
  files:
    ignoreRules:
      - "lost+found"
      - "*/lost+found"
  repository:
    kind: ClusterRepository
    name: ragnar
  retention:
    keepDaily: 7
    keepHourly: 24
  sources:
    - pvc:
        name: ${KOPIUR_CLAIM:=${APP}}
  mover:
    podSecurityContext:
      fsGroup: ${KOPIUR_PGID:=2000}
    securityContext:
      runAsUser: ${KOPIUR_PUID:=2000}
      runAsGroup: ${KOPIUR_PGID:=2000}
      runAsNonRoot: ${KOPIUR_RUNASNONROOT:=true}
    privilegedMode: true
  verification:
    deep:
      schedule:
        cron: H 5 * * 0
        timezone: America/New_York
    quick:
      schedule:
        cron: H 5 * * *
        timezone: America/New_York
  volumeSnapshotClassName: ${KOPIUR_SNAPSHOTCLASS:=csi-ceph-blockpool}
