---
# yaml-language-server: $schema=https://schemas.zinn.ca/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: issueboss
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: issueboss-secret
    creationPolicy: Owner
    template:
      data:
        # issueboss
        ISSUEBOSS__DATABASE__DATABASE_URL: "postgres://{{ .DB_USERNAME }}:{{ .DB_PASSWORD }}@postgres-18-rw.dbms.svc.cluster.local.:5432/issueboss"
        # Postgres Init
        INIT_POSTGRES_DBNAME: issueboss
        INIT_POSTGRES_HOST: postgres-18-rw.dbms.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .DB_USERNAME }}"
        INIT_POSTGRES_PASS: "{{ .DB_PASSWORD }}"
        INIT_POSTGRES_SUPER_USER: "{{ .POSTGRES_SUPER_USER }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: issueboss
    - extract:
        key: cloudnative-pg-superuser
