---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  dependsOn:
    - name: snapshot-controller
      namespace: system
  values:
    crds:
      enabled: true
    csi:
      serviceMonitor:
        enabled: true
    image:
      repository: ghcr.io/rook/ceph
    monitoring:
      enabled: true
    resources:
      requests:
        memory: 128Mi # unchangable
        cpu: 100m # unchangable
      limits: {}
