---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kopiur
spec:
  chartRef:
    kind: OCIRepository
    name: kopiur
  interval: 1h
  values:
    # logging:
    #   level: debug,kopia=debug
    extraVolumes:
      - name: repo
        nfs:
          server: ragnar.zinn.tech
          path: /mnt/atlas/k8s/staging/kopiur
    extraVolumeMounts:
      - name: repo
        mountPath: /repo
    monitoring:
      dashboards:
        enabled: false
        grafanaOperator:
          enabled: false
          matchLabels:
            dashboards: grafana
      prometheusRule:
        enabled: false
      serviceMonitor:
        enabled: false
    podSecurityContext:
      runAsNonRoot: true
      runAsUser: 2000
      runAsGroup: 2000
      fsGroup: 2000
      fsGroupChangePolicy: OnRootMismatch
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 2Gi
