---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rook-ceph-operator
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: rook-ceph
  dependsOn:
    - name: snapshot-controller
      namespace: system
  values:
    image:
      repository: ghcr.io/rook/ceph
    crds:
      enabled: true
    monitoring:
      enabled: true
    resources:
      requests:
        cpu: 109m
        memory: 204Mi
      limits: {}
