---
# yaml-language-server: $schema=https://schemas.zinn.ca/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: seerr
spec:
  targetNamespace: downloads
  path: ./kubernetes/main/apps/downloads/seerr/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  dependsOn:
    - name: external-secrets
      namespace: external-secrets
    - name: rook-ceph-cluster
      namespace: rook-ceph
  components:
    - ../../../../components/volsync
    - ../../../../components/zeroscaler
  postBuild:
    substitute:
      APP: seerr
      VOLSYNC_CLAIM: seerr-config
      VOLSYNC_CAPACITY: 5Gi
  prune: true
  wait: false
  interval: 1h
  timeout: 5m
