apiVersion: gateway.networking.k8s.io/v1
kind: GRPCRoute
metadata:
  name: bookboss
spec:
  hostnames:
    - bookboss.zinn.ca
  parentRefs:
    - name: envoy-internal
      namespace: network
      sectionName: grpc
  rules:
    - backendRefs:
        - name: bookboss
          port: 8081
