---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: bookboss
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      bookboss:
        strategy: Recreate
        annotations:
          secret.reloader.stakater.com/reload: bookboss-secret
        pod:
          enableServiceLinks: false
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
            runAsNonRoot: true
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          init-db:
            image:
              repository: ghcr.io/home-operations/postgres-init
              tag: 18.3@sha256:6fa1f331cddd2eb0b6afa7b8d3685c864127a81ab01c3d9400bc3ff5263a51cf
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: bookboss-secret
        containers:
          bookboss:
            image:
              repository: ghcr.io/szinn/bookboss
              tag: v0.7.12@sha256:60fa690f339ea2192261268eced4c5ddd6625c867064497b0cf268cb4ab47556
            env:
              BOOKBOSS__FRONTEND__BASE_URL: "https://bookboss.zinn.ca"
              BOOKBOSS__LIBRARY__LIBRARY_PATH: "/library/books"
              BOOKBOSS__IMPORT__BOOKDROP_PATH: "/library/bookdrop"
              BOOKBOSS__IMPORT__POLL_INTERVAL_SECS: 60
              BOOKBOSS__IMPORT__WORKER_POLL_INTERVAL_SECS: 5
              TZ: "America/Toronto"
              RUST_LOG: "TRACE"
            envFrom:
              - secretRef:
                  name: bookboss-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /healthz
                    port: &port 8080
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /readyz
                    port: *port
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
    service:
      bookboss:
        ports:
          http:
            port: *port
            primary: true
          grpc:
            port: 8081
            targetPort: 8081
            appProtocol: grpc

    route:
      internal:
        annotations:
          gatus.home-operations.com/endpoint: |
            url: "https://{{ .Release.Name }}.zinn.ca/healthz"
            conditions: ["[STATUS] == 200"]
        hostnames:
          - "{{ .Release.Name }}.zinn.ca"
        parentRefs:
          - name: envoy-internal
            namespace: network

    persistence:
      library:
        type: nfs
        server: ragnar.zinn.tech
        path: /mnt/atlas/media
        advancedMounts:
          bookboss:
            bookboss:
              - path: /library/books
                subPath: BookLibrary/Books
              - path: /library/bookdrop
                subPath: BookLibrary/Bookdrop
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
