---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grimmory
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      grimmory:
        annotations:
          reloader.stakater.com/auto: "true"
        pod:
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
            fsGroup: 1000
            fsGroupChangePolicy: OnRootMismatch
        initContainers:
          mariadb:
            image:
              repository: docker.io/library/mariadb
              tag: 12.2.2-noble@sha256:e16f61b8f6ed25111adbb1c5c19bbc2904efc8ed14029999af0cbe1c7ae18bf1
            env:
              TZ: America/Toronto
              MARIADB_DATABASE: grimmory
              MARIADB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: grimmory_mariadb_password
              MARIADB_ROOT_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: grimmory_mariadb_root_password
              MARIADB_USER: grimmory
              PGID: 1000
              PUID: 1000
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  exec:
                    command:
                      - bash
                      - -c
                      - |-
                        mariadb-admin ping --socket=/run/mysqld/mysqld.sock --user=root --password=$${MARIADB_ROOT_PASSWORD}
            restartPolicy: Always
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
              # NOTE: io_uring is blocked by the default containerd v2 seccomp profile
              # https://github.com/containerd/containerd/pull/9320
              seccompProfile: { type: Unconfined }
          wait-for-mariadb:
            image:
              repository: wait4x/wait4x
              tag: 3.6.0@sha256:bec7ac18547781d854562c3729d3195c3880116d6758c49fdf4573ad58805f14
            args:
              - "mysql"
              - "grimmory:$(DB_PASSWORD)@tcp(localhost:3306)/grimmory"
            env:
              DB_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: grimmory_mariadb_password
        containers:
          grimmory:
            image:
              repository: ghcr.io/grimmory-app/grimmory
              tag: v2.2.1@sha256:252586c469ff6d07a06469fd1d49f19af932f4d323713d253c5d29e33b6ec97a
            command:
              - java
            args:
              - -jar
              - /app/app.jar
            env:
              TZ: America/Toronto
              LOG_LEVEL: "DEBUG"
              DATABASE_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: grimmory-secret
                    key: grimmory_mariadb_password
              DATABASE_URL: jdbc:mariadb://localhost:3306/grimmory
              DATABASE_USERNAME: grimmory
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: &httpPort 6060
                  periodSeconds: 30
                  timeoutSeconds: 5
                  failureThreshold: 5
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/v1/healthcheck
                    port: *httpPort
                  periodSeconds: 10
                  timeoutSeconds: 5
                  failureThreshold: 5
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true
    persistence:
      data:
        existingClaim: grimmory-config
        advancedMounts:
          grimmory:
            grimmory:
              - path: /app/data
                subPath: app
            mariadb:
              - path: /var/lib/mysql
                subPath: mysql
      nfs-nas-media:
        type: nfs
        server: ragnar.zinn.tech
        path: /mnt/atlas/media
        advancedMounts:
          grimmory:
            grimmory:
              - path: /books
                subPath: Grimmory/Books
              - path: /bookdrop
                subPath: Grimmory/Bookdrop
              - path: /tmp
                subPath: Grimmory/tmp
      mysqld:
        type: emptyDir
        medium: Memory
        sizeLimit: 1Mi
        advancedMounts:
          grimmory:
            mariadb:
              - path: /run/mysqld
      tmpfs:
        type: emptyDir
        medium: Memory
        sizeLimit: 100Mi
        advancedMounts:
          grimmory:
            # grimmory:
            #   - path: /tmp
            #     subPath: app
            mariadb:
              - path: /tmp
                subPath: mysql
    route:
      grimmory:
        hostnames:
          - "{{ .Release.Name }}.zinn.ca"
        parentRefs:
          - name: envoy-internal
            namespace: network
    service:
      grimmory:
        ports:
          http:
            port: *httpPort
