---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pdf-tool
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      pdf-tool:
        containers:
          pdf-tool:
            image:
              repository: ghcr.io/stirling-tools/s-pdf
              tag: 2.14.1@sha256:986ae1d17bd41661351006526332a29a1ff7ca6799e69a51a8bb549c55941044
              pullPolicy: IfNotPresent
            envFrom:
              - secretRef:
                  name: pdf-tool-secret
    service:
      pdf-tool:
        ports:
          http:
            port: 8080
    route:
      internal:
        annotations:
          gatus.home-operations.com/endpoint: |-
            conditions: ["[STATUS] == 401"]
        hostnames: ["{{ .Release.Name }}.zinn.ca"]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        existingClaim: pdf-tool-config
        globalMounts:
          - path: /configs
      tessdata:
        enabled: true
        type: emptyDir
        globalMounts:
          - path: /usr/share/tessdata
