---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mailkeep
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mailkeep-secret
    creationPolicy: Owner
    template:
      data:
        MAILKEEP__ENCRYPTION_SECRET: "{{ .ENCRYPTION_SECRET }}"
        MAILKEEP__OIDC__DISCOVERY_URL: "https://auth.zinn.ca/oauth2/openid/mailkeep/.well-known/openid-configuration"
        MAILKEEP__OIDC__CLIENT_ID: "mailkeep"
        MAILKEEP__OIDC__CLIENT_SECRET: "{{ .OAUTH_CLIENT_SECRET }}"
  dataFrom:
    - extract:
        key: mailkeep
