---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lissy93/dashy
              tag: 4.2.5@sha256:69a765f96900da5d22a5f88e6801b273b4b939bfd3b8beed48ae935152f7cc85
            env:
              TZ: America/Toronto
              DISABLE_CONFIG_BACKUPS: true
    service:
      main:
        ports:
          http:
            port: &mainPort 8080
    route:
      main:
        hostnames: ["dashy.test.zinn.ca"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: main
                port: *mainPort
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /app/user-data
      icons:
        enabled: true
        type: configMap
        name: dashy-icons
        advancedMounts:
          main:
            main:
              - path: /app/user-data/item-icons
                readOnly: true
