---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dashy
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: ghcr.io/lissy93/dashy
              tag: 3.1.2@sha256:2eb764df4f24878eda9ae664d91c50f32eebf41c9e35faf99dddc2e77853ab5d
            env:
              TZ: America/Toronto
              UID: 2000
              GID: 2000
          code-server:
            image:
              repository: ghcr.io/coder/code-server
              tag: 4.110.0@sha256:d56097319b62b1f34e3b919ddbb7ccb90fc1d98bdb69802fb92831a16d9300d3
            securityContext:
              runAsUser: 0
            args:
              [
                "--auth",
                "none",
                "--disable-telemetry",
                "--disable-update-check",
                "--user-data-dir",
                "/tmp/.vscode",
                "--extensions-dir",
                "/tmp/.vs1ode",
                "--port",
                "8081",
                "/config"
              ]
    service:
      main:
        ports:
          http:
            port: &mainPort 8080
      code-server:
        ports:
          http:
            port: &codePort 8081
    route:
      main:
        hostnames: ["dashy.test.zinn.ca"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: main
                port: *mainPort
      code-server:
        hostnames: ["dashy-code.test.zinn.ca"]
        parentRefs:
          - name: envoy-internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: code-server
                port: *codePort
    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /app/user-data
            code-server:
              - path: /config
      icons:
        enabled: true
        type: configMap
        name: dashy-icons
        advancedMounts:
          main:
            main:
              - path: /app/user-data/item-icons
                readOnly: true
      temp:
        enabled: true
        type: emptyDir
        advancedMounts:
          main:
            code-server:
              - path: /tmp/.vscode
