---
apiVersion: v1
kind: Namespace
metadata:
  name: _
  annotations:
    volsync.backube/privileged-movers: "true"
    kustomize.toolkit.fluxcd.io/prune: disabled
    kopiur.home-operations.com/privileged-movers: "true"
