---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cardigan
spec:
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: cardigan-secret
    creationPolicy: Owner
    template:
      data:
        CARDIGAN_ICLOUD_USERNAME: "{{ .ICLOUD_USERNAME }}"
        CARDIGAN_ICLOUD_PASSWORD: "{{ .ICLOUD_PASSWORD }}"
        CARDIGAN_FASTMAIL_USERNAME: "{{ .FASTMAIL_USERNAME }}"
        CARDIGAN_FASTMAIL_PASSWORD: "{{ .FASTMAIL_PASSWORD }}"
  dataFrom:
    - extract:
        key: cardigan
