---
# yaml-language-server: $schema=https://schemas.zinn.ca/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-18
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.3@sha256:766a236947fe082987bdb07d5a5bc9dca0f0ad4204d77de03cbefb14333b645d
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 100Gi
    storageClass: openebs-hostpath

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      wal_keep_size: 2GB

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  monitoring:
    enablePodMonitor: true
