---
# yaml-language-server: $schema=https://schemas.zinn.ca/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres-18
  labels:
    app.kubernetes.io/name: postgres-db
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18.4@sha256:7a9a68272eb5f192c5826fdd72b1ebc81c185fea21678993c5583610c7e59739
  instances: 3
  primaryUpdateStrategy: unsupervised

  storage:
    size: 100Gi
    storageClass: openebs-hostpath

  enableSuperuserAccess: true
  superuserSecret:
    name: postgres-superuser

  postgresql:
    parameters:
      max_connections: "300"
      shared_buffers: 512MB
      wal_keep_size: 2GB

  affinity:
    enablePodAntiAffinity: true
    topologyKey: kubernetes.io/hostname
    podAntiAffinityType: required

  monitoring:
    enablePodMonitor: true
