---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: homepage
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  values:
    controllers:
      main:
        replicas: 1
        strategy: RollingUpdate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/gethomepage/homepage
              tag: v1.11.0@sha256:b129cb0f674bd6d204e215bde2c2fc3f11d6ad0e82f6d20007cf80f74e1acbb1
            env:
              HOMEPAGE_ALLOWED_HOSTS: &host "{{ .Release.Name }}.zinn.ca"
              TZ: America/Toronto
            envFrom:
              - secretRef:
                  name: homepage-secret
            resources:
              requests:
                cpu: 15m
                memory: 200M
              limits:
                memory: 2G
    service:
      main:
        ports:
          http:
            port: 3000
    route:
      internal:
        hostnames: [*host]
        parentRefs:
          - name: envoy-internal
            namespace: network
    persistence:
      config:
        type: configMap
        name: homepage-config
        globalMounts:
          - subPath: bookmarks.yaml
            path: /app/config/bookmarks.yaml
          - subPath: docker.yaml
            path: /app/config/docker.yaml
          - subPath: kubernetes.yaml
            path: /app/config/kubernetes.yaml
          - subPath: services.yaml
            path: /app/config/services.yaml
          - subPath: settings.yaml
            path: /app/config/settings.yaml
          - subPath: widgets.yaml
            path: /app/config/widgets.yaml
    serviceAccount:
      homepage: {}
