---
services:
  gatus:
    image: ghcr.io/twin/gatus:v5.24.3@sha256:19b064c8be229df4848475f5e07f7dcd19cabbe8c27ea7ed6ff0e5af8e2050b6
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8443:8443
    volumes:
      - /opt/gatus:/config
      - /opt/certificates:/config/certificates
    networks:
      - backend

networks:
  backend: {}
