---
services:
  gatus:
    image: ghcr.io/twin/gatus:v5.37.0@sha256:094eb186e55235db367e90e9d56140e5897b7044c41de23cde4cc18e6da1242e
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8443:8443
    volumes:
      - /opt/gatus:/config
      - /opt/certificates:/config/certificates
    networks:
      - backend

networks:
  backend: {}
