---
services:
  gatus:
    image: ghcr.io/twin/gatus:v5.24.1@sha256:fcd3ba5a7d7db6c1c83780529cd69f249d1dff6deaffcdb6729ac804fe3d4444
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 8443:8443
    volumes:
      - /opt/gatus:/config
      - /opt/certificates:/config/certificates
    networks:
      - backend

networks:
  backend: {}
