---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Link Checker

on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

env:
  WORKFLOW_ISSUE_TITLE: "Link Checker Dashboard 🔗"

permissions:
  contents: read
  issues: write

jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    steps:
      - name: Load Secrets
        id: load-secrets
        uses: 1password/load-secrets-action@3a12b0ab99d9cd590a3e9b5a90ea017210ed9556 # v4.0.1 # zizmor: ignore[unpinned-tools]
        env:
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
          GITHUB_BOT_APP_CLIENT_ID: op://Kubernetes/github-jeeves/GITHUB_APP_CLIENT_ID
          GITHUB_BOT_APP_PRIVATE_KEY: op://Kubernetes/github-jeeves/GITHUB_APP_PRIVATE_KEY

      - name: Generate Token
        uses: actions/create-github-app-token@bcd2ba49218906704ab6c1aa796996da409d3eb1 # v3.2.0
        id: app-token
        with:
          client-id: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_CLIENT_ID }}
          private-key: ${{ steps.load-secrets.outputs.GITHUB_BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          token: "${{ steps.app-token.outputs.token }}"

      - name: Setup Homebrew
        uses: Homebrew/actions/setup-homebrew@2825979605fed985cccfbd7f3dc3188161aaa15e # master

      - name: Setup Workflow Tools
        shell: bash
        run: brew install lychee

      - name: Scan For Broken Links
        shell: bash
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          lychee --verbose --no-progress \
              --format markdown \
              --output results.md \
              --exclude-all-private \
              ./**/*.md || true

      - name: Print Output
        run: cat results.md

      - name: Find Link Checker Issue
        id: find-issue
        shell: bash
        env:
          GH_TOKEN: "${{ steps.app-token.outputs.token }}"
        run: |
          issue_number=$( \
              gh issue list \
                  --search "in:title ${{ env.WORKFLOW_ISSUE_TITLE }}" \
                  --state open \
                  --json number \
                  | jq --raw-output '.[0].number' \
          )
          echo "issue-number=${issue_number}" >> "${GITHUB_OUTPUT}"
          echo "${issue_number}"

      - name: Create or Update Issue
        uses: peter-evans/create-issue-from-file@fca9117c27cdc29c6c4db3b86c48e4115a786710 # v6
        with:
          token: "${{ steps.app-token.outputs.token }}"
          title: "${{ env.WORKFLOW_ISSUE_TITLE }}"
          issue-number: "${{ steps.find-issue.outputs.issue-number || '' }}"
          content-filepath: results.md
